# Site settings
title: Formikation
email: kespers@gmail.com
description: >
  Formikation is a simple jQuery plugin to beautify form inputs with some css.
baseurl: "/formikation"
url: "http://vortizhe.me"

# Build settings
markdown: redcarpet
highlighter: pygments
fenced_code_blocks: true
redcarpet:
 extensions: ["fenced_code_blocks", "tables"]
github: [Repository metadata]

gems:
  - jekyll-sitemap

# Plugins
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/feed.xml"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
