# Site settings
title: Formikation
email: kespers@gmail.com
description: >
  Formikation is a simple jQuery plugin to beautify form inputs with some css.
baseurl: "/formikation"
url: "http://vortizhe.me"

# Build settings
github: [Repository metadata]

kramdown:
  hard_wrap: false
  input: GFM

gems:
  - jekyll-sitemap

# Plugins
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/feed.xml"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
